import { test, expect } from '@playwright/test';

test('test', async ({ page}) => {
    const email = `wonikatest${Date.now()}@yopmail.com`;
  await page.goto('https://authorized-partner.vercel.app/');
  await page.getByRole('link', { name: 'Get Started' }).getByRole('button').click();
  await page.getByRole('checkbox', { name: 'I agree to the Terms of' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Wonika');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill(email);
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('9841888888');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('Test@123');
  await page.locator('input[name="confirmPassword"]').click();
  await page.locator('input[name="confirmPassword"]').fill('Test@123');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.pause();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Wonika');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill(email);
  await page.getByRole('textbox', { name: 'Address', exact: true }).click();
  await page.getByRole('textbox', { name: 'Address', exact: true }).fill('sanepa');
  await page.getByRole('textbox', { name: 'Role in Agency' }).click();
  await page.getByRole('textbox', { name: 'Role in Agency' }).fill('Intern');
  await page.getByRole('textbox', { name: 'Website' }).click();
  await page.getByRole('textbox', { name: 'Website' }).fill('www.testwebsite.com');
  await page.getByRole('combobox').click();
  await page.locator('div').filter({ hasText: /^Nepal$/ }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('combobox', { name: 'Years of Experience' }).click();
  await page.getByRole('option', { name: '1 year' }).click();
  await page.getByRole('textbox', { name: 'Focus Area' }).click();
  await page.getByRole('textbox', { name: 'Focus Area' }).fill('Undergraduate Counseling');
  await page.getByRole('spinbutton', { name: 'Number of Students Recruited' }).click();
  await page.getByRole('spinbutton', { name: 'Number of Students Recruited' }).fill('100');
  await page.getByRole('spinbutton', { name: 'Success Metrics' }).click();
  await page.getByRole('spinbutton', { name: 'Success Metrics' }).fill('76');
  await page.getByRole('checkbox', { name: 'Career Counseling' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Business Registration Number' }).click();
  await page.getByRole('textbox', { name: 'Business Registration Number' }).fill('9841888888');
  await page.getByRole('combobox', { name: 'Preferred Countries' }).click();
  await page.getByRole('textbox', { name: 'Search...' }).fill('un');
  await page.getByText('United States of America').click();
  await page.getByRole('checkbox', { name: 'Universities' }).click();
  await page.getByText('Upload a file or drag and dropPNG, JPG, PDF, DOCS, XLSX, CSV, PPT up to 5MB').first().click();
  await page.getByRole('button', { name: 'Choose File' }).first().setInputFiles('Test File.docx');
  await page.locator('.flex.flex-col.items-center').first().press('Enter');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://authorized-partner.vercel.app/admin/profile');
});